name: CI & Despliegue a GitHub Pages

on:
  push:
    branches: ["main", "frontend"] # Se activa con cada push a la rama 'main'
  pull_request:
    branches: ["main"] # También se activa con cada Pull Request
  workflow_dispatch: # Permite ejecución manual

concurrency:
  group: 'CI-CD-GHPages'
  cancel-in-progress: true

jobs:
  # Job 1: Verificación de Código (LINTING BÁSICO)
  verificar_codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: 🔍 Mostrar archivos (Opcional, para depurar)
        run: ls -R


      - name: Verificar existencia de home.html y styles.css o css.html
        run: |
            if [ -f index.html ] && [ -f styles.css ]; then
               echo "Archivos HTML y CSS encontrados. ¡CI Básico Superado!"
            else
               echo "Error: Faltan archivos index.html o styles.css"
               exit 1
            fi

  deploy:
      needs: verificar_codigo
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
      
      permissions:
          contents: read
          pages: write
          id-token: write
  
      steps:
          - name: Checkout del Repositorio
            uses: actions/checkout@v4

          - name: Simulcacion de preparacion de artefactos para Staging
            run: echo "Artefactos listos para el despliegue en el entorno de Staging"
        
          - name: Configurar GitHub Pages
            uses: actions/configure-pages@v5
        
          - name: Subir Artifactos de Despliegue
            uses: actions/upload-pages-artifact@v3
            with:
            # El directorio que contiene tus archivos HTML y CSS
              path: './'
        
          - name: Iniciar Despliegue a Pages
            id: deployment
            uses: actions/deploy-pages@v4